class SavedSearch < ActiveRecord::Base

  # relations
  # note currently no support for nullable user (because the user field is the creator_id field
  # automatically generated by userstamps)

  # attr
  attr_accessible :name, :search_object

  # userstamp
  stampable
  belongs_to :user, :class_name => 'User', :foreign_key => :creator_id

  # validation
  validates :search_object, :presence => true

  validates_uniqueness_of :search_object,
                          :scope => [:creator_id, :name]
end
