class SavedSearch < ActiveRecord::Base

  # relations
  # note currently no support for nullable user (because the user field is the creator_id field
  # automatically generated by userstamps)
  has_many :progresses

  # attr
  attr_accessible :name,
                  :search_object    # a string (text type) based representation of a saved search
                                    #   the format is json

  # userstamp
  stampable
  belongs_to :user, :class_name => 'User', :foreign_key => :creator_id

  # validation
  validates :search_object, :presence => true

  validates_uniqueness_of :search_object,
                          :scope => [:creator_id, :name]
end
